"use client";
import './globals.css'
import {ThemeProvider} from '@/themes'
import { SessionProvider } from "next-auth/react";
import { AuthProvider } from '@/context';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
      <SessionProvider>
          <AuthProvider>
            <ThemeProvider>
              {children}
            </ThemeProvider>
          </AuthProvider>
      </SessionProvider>
      </body>
    </html>
  )
}
